# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: awskeys

stages:
  - stage: init
    displayName: "Copying repo" 
    jobs:
     - job: Repo_clone
       steps:
         - task: TerraformInstaller@2
           displayName: 'Install terraform'
           inputs:
             terraformVersion: 'latest'
            
         - task: TerraformCLI@2
           displayName: 'Terraform init'
           inputs:
             command: 'init'
             allowTelemetryCollection: true
             
         - task: TerraformCLI@2
           displayName: 'Terraform validate'
           inputs:
             command: 'validate'
             allowTelemetryCollection: true
             
         - task: TerraformCLI@2
           displayName: 'Terraform Plan'
           inputs:
             command: 'plan'
             environmentServiceName: 'AN-serviceconnection'
             commandOptions: '-var "aws_access_key=$(accesskey)" -var "aws_secret_key=$(secretkey)"'
             allowTelemetryCollection: false
             providerServiceAws: 'AWSconnection'
             providerAwsRegion: 'us-west-2'
             

         - task: TerraformCLI@2
           inputs:
             command: 'apply'
             environmentServiceName: 'AN-serviceconnection'
             allowTelemetryCollection: true
             providerServiceAws: 'AWSconnection'
         
